version: "3.9"
services: 
  app:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USERNAME=phuoclong
      - DB_PASSWORD=51648951354
      - DB_NAME=Todo
    ports:
      - "8080:5000"
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phuoclong
      - MONGO_INITDB_ROOT_PASSWORD=5164895134
    volumes:
      - ./data:/usr/src/data/db
    ports:
      - "27017:27017"
    depends_on:
      - app


    

